name: emprestapro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.3.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.1.0
  flutter_secure_storage: ^9.2.2
  flutter_timezone: ^4.1.0
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  mailer: ^6.2.0
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  permission_handler: ^11.0.0
  flutter_bloc: ^9.1.0
  workmanager: ^0.5.2

dependency_overrides:
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/chart.png
    - assets/images/black_cilinder.png
    - assets/images/orange_cilinder.png
    - assets/images/black_circle.png
    - assets/images/google_logo.png
    - assets/images/whatsapp_logo.png
