name: emprestapro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  get_it: ^7.7.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  twilio: ^0.0.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dependency_overrides:
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_nome.png
    - assets/images/chart.png
    - assets/images/black_cilinder.png
    - assets/images/orange_cilinder.png
    - assets/images/black_circle.png
